### ISSUE TITLE
Unbounded maximum likelihood

### ISSUE THREAD

**Issue by daisy12321** [cvxgrp/Convex.jl#46]
Hello!

I am using convex.jl to test and see if it works on a simple maximum likelihood estimator for logistic regression. It is giving me unbounded results though - I am not sure if it's an issue with my formulation or something else. Would you be able to take a quick look and let me know where I may have made a mistake? Thank you very much in advance!

```Julia

using DataFrames
using RDatasets
using Convex
using SCS

iris = dataset("datasets", "iris")
iris[:Y] = [species == "versicolor" ? 1.0 : 0.0 for species in iris[:Species]]
X = [ones(size(iris, 1)) iris[:SepalLength] iris[:SepalWidth] iris[:PetalLength] iris[:PetalWidth]]
Y = array(iris[:Y])

# Solve the NLP using Convex.jl and SCS packages
# reference: http://cvxr.com/cvx/examples/cvxbook/Ch07_statistical_estim/html/logistics.html
n, p = size(X)
beta = Variable(p)
problem = maximize(Y'*X*beta-sum(logsumexp([X*beta zeros(n)]))) # -0.01*norm(beta,1)


scs = SCSSolver()
solve!(problem, scs)
```

Output:
```
Setup time: 8.27e-04s
----------------------------------------------------------------------------
 Iter | pri res | dua res | rel gap | pri obj | dua obj | kap/tau | time (s)
----------------------------------------------------------------------------
     0|      inf       inf       nan      -inf       inf       inf  3.44e-03 
    40|      inf       inf       nan      -inf      -inf       inf  5.09e-03 
----------------------------------------------------------------------------
Status: Unbounded
```

**Comment by madeleineudell** [comment]
Hi Daisy,

It looks like you need to use labels +-1, rather than 0 and 1. There's also
an easier way of writing logistic regression in Convex.jl. If you pull the
most recent version from master, this should work:

using DataFrames
using RDatasets
using Convex
using SCS

iris = dataset("datasets", "iris")
iris[:Y] = [species == "versicolor" ? 1.0 : -1.0 for species in
iris[:Species]]
X = [ones(size(iris, 1)) iris[:SepalLength] iris[:SepalWidth]
iris[:PetalLength] iris[:PetalWidth]]
Y = array(iris[:Y])

# Solve the NLP using Convex.jl and SCS packages
# reference:
http://cvxr.com/cvx/examples/cvxbook/Ch07_statistical_estim/html/logistics.html
n, p = size(X)
beta = Variable(p)
problem = minimize(sum([logistic_loss(-Y[i]*(X[i,:]*beta)) for i=1:n])) #
-0.01*norm(beta,1)

scs = SCSSolver()
solve!(problem, scs)

and you can plot the solution like this:

using Gadfly
perm = Base.Sort.sortperm(vec(X*beta.value))
set_default_plot_size(25cm, 12cm)
plot(layer(x=1:n,y=(Y[perm]+1)/2,Geom.point),layer(x=1:n,y=logistic(X*beta.value)[perm],Geom.line))

[image: Inline image 1]

Best,
Madeleine

On Wed, Jan 7, 2015 at 10:09 AM, Daisy Zhuo <notifications@github.com>
wrote:

> Hello!
>
> I am using convex.jl to test and see if it works on a simple maximum
> likelihood estimator for logistic regression. It is giving me unbounded
> results though - I am not sure if it's an issue with my formulation or
> something else. Would you be able to take a quick look and let me know
> where I may have made a mistake? Thank you very much in advance!
>
> using DataFramesusing RDatasetsusing Convexusing SCS
>
> iris = dataset("datasets", "iris")
> iris[:Y] = [species == "versicolor" ? 1.0 : 0.0 for species in iris[:Species]]
> X = [ones(size(iris, 1)) iris[:SepalLength] iris[:SepalWidth] iris[:PetalLength] iris[:PetalWidth]]
> Y = array(iris[:Y])
> # Solve the NLP using Convex.jl and SCS packages# reference: http://cvxr.com/cvx/examples/cvxbook/Ch07_statistical_estim/html/logistics.html
> n, p = size(X)
> beta = Variable(p)
> problem = maximize(Y'*X*beta-sum(logsumexp([X*beta zeros(n)]))) # -0.01*norm(beta,1)
>
>
> scs = SCSSolver()solve!(problem, scs)
>
> Output:
>
> Setup time: 8.27e-04s
> ----------------------------------------------------------------------------
>  Iter | pri res | dua res | rel gap | pri obj | dua obj | kap/tau | time (s)
> ----------------------------------------------------------------------------
>      0|      inf       inf       nan      -inf       inf       inf  3.44e-03
>     40|      inf       inf       nan      -inf      -inf       inf  5.09e-03
> ----------------------------------------------------------------------------
> Status: Unbounded
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cvxgrp/Convex.jl/issues/46>.
>



-- 
Madeleine Udell
PhD Candidate in Computational and Mathematical Engineering
Stanford University
www.stanford.edu/~udell

**Comment by daisy12321** [comment]
Hi Madeleine,

This works like a charm. Logistic loss and using +1/-1 labels does make it look neater and run correctly.

Thank you very much!

Cheers,
Daisy
